- hosts: default
  become: yes

  tasks:

    - name: Install Apache2
      apt: 
        name: apache2
        state: present

    - name: Install MySQL packages
      apt: name={{item}} state=present
      with_items:
        - mysql-server
        - php5-mysql
        - python-mysqldb

    - name: Install PHP packages
      apt: name={{item}} state=present
      with_items:
        - php5
        - libapache2-mod-php5
        - php5-mcrypt

    - name: Create a new database with name wordpress_db
      mysql_db:
        name: wordpress_db
        state: present
        
    - name: Create WordPress database user
      mysql_user:
        #login_user: root
        #login_password: "{{ mysql_root_db_password }}"
        #login_password: password
        name: wordpress
        password: Pa55w0rd
        priv: "wordpress_db.*:ALL"
        host: localhost
        state: present
        #check_implicit_admin: true      

    - name: Download WordPress
      get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/tmp/wordpress-{{ wp_version }}.tar.gz

    - name: Extract archive
      command: chdir=/var/www/html/ /bin/tar xvf /tmp/wordpress-{{ wp_version }}.tar.gz  