- hosts: default
  become: yes

  tasks:

    - name: Install Apache2
      apt: 
        name: apache2
        state: present

    - name: Install MySQL packages
      apt: name={{item}} state=present
      with_items:
        - mysql-server
        - php5-mysql
        - python-mysqldb

    - name: Install PHP packages
      apt: name={{item}} state=present
      with_items:
        - php5
        - libapache2-mod-php5
        - php5-mcrypt

    - name: Create a new database
      mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: Create WordPress database user
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ db_name }}.*:ALL"
        host: localhost
        state: present   

    - name: Download WordPress
      get_url: 
        url: http://wordpress.org/wordpress-{{ wp_version }}.tar.gz 
        dest: /tmp/wordpress-{{ wp_version }}.tar.gz
        mode: 0755

    - name: Creates directory
      file:
        path: /var/www/html/{{ site_name }}
        state: directory
        owner: root
        group: root
        mode: 0655

    - name: Extract archive
      command: chdir=/var/www/html/{{ site_name }} /bin/tar xvf /tmp/wordpress-{{ wp_version }}.tar.gz --strip-components 1 warn=false

    - name: Wordpress config file
      template:
        src: wp-config.php
        dest: /var/www/html/{{ site_name }}
        owner: root
        group: root
        mode: '0655'