- hosts: default
  become: yes

  tasks:

    - name: Install Apache2
      apt: 
        name: apache2
        state: present

    - name: Install MySQL packages
      apt: name={{item}} state=present
      with_items:
        - mysql-server
        - php5-mysql  
