---
- hosts: default

  tasks:

    - name: Verify required variables
      fail: msg="Variable '{{ item }}' is not defined"
      when: item not in vars
      with_items:
         - wp_version
         - hostname
         - db_name
         - mysql_user
         - site_name

    - name: install python 2, if needed
      become: yes
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: no

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Get iptables rules
      become: yes
      shell: iptables -L
      register: iptablesrules
     
    - name: Apache | add apache iptable rule
      become: yes
      command: /sbin/iptables -I INPUT 1 -p tcp --dport http -j ACCEPT -m comment --comment "Apache"
      when: iptablesrules.stdout.find("Apache") == -1

    - name: ssh | add ssh iptable rule
      become: yes
      command: /sbin/iptables -I INPUT 1 -p tcp --dport ssh -j ACCEPT -m comment --comment "ssh"
      when: iptablesrules.stdout.find("ssh") == -1  
     
    - name: save iptables
      become: yes
      command: iptables-save
     
    - name: restart iptables
      become: yes
      service: 
        name: ufw 
        state: restarted    

- import_playbook: lampstack.yml